development:
  adapter: postgresql
  encoding: unicode
  database: mobileapp
  pool: 2
  username:
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: mobileapp
  pool: 2
  username:
  password:
